PUS_PER_NODE=4 ./tools/run_dist_launch.sh 4 ./configs/dn_detr.sh \
    --batch_size 10 \
    --model_name dn_detr \
    --use_dn \
    --coco_path "../COCODIR/" \
    --output_dir "./logs/upperbound" \
    --num_workers 16  \
    --Task 1 \
    --Task_Epochs 50 \
    --start_epoch 0 \
    --CL_Limited 0 \
    --verbose  \
    --Total_Classes 90 \
    --limit_image 1000 \
    --least_image 30 \
    --save_log \
    --save_results \